quality:
  image: python:3.7-slim-buster
  before_script:
    - pip install isort black flake8 pylint
  script:
    - isort -check-only --profile black .
    - black --check .
    - flake8 .
    - touch __init__.py; pylint $(pwd); rm __init__.py
