stages:
  - quality_checking

isort:
  stage: quality_checking
  image: python:3.7-slim-buster
  before_script:
    - pip install isort
  script:
    - isort --check-only --profile black .
  only:
    - merge_requests

black:
  stage: quality_checking
  image: python:3.7-slim-buster
  before_script:
    - pip install black
  script:
    - black --check .
  only:
    - merge_requests

flake8:
  stage: quality_checking
  image: python:3.7-slim-buster
  before_script:
    - pip install flake8
  script:
    - flake8 --extend-ignore E203,E501 .
  only:
    - merge_requests

pylint:
  stage: quality_checking
  image: python:3.7-slim-buster
  before_script:
    - pip install pylint
    - touch __init.py
  script:
    pylint $(pwd)
