stages:
  - quality_checking
  - run
  - tests

isort:
  stage: quality_checking
  image: python:3.7-slim-buster
  before_script:
    - pip install isort
  script:
    - isort --check-only --profile black .
  only:
    - merge_requests

black:
  stage: quality_checking
  image: python:3.7-slim-buster
  before_script:
    - pip install black
  script:
    - black --check .
  only:
    - merge_requests

# flake8:
#   stage: quality_checking
#   image: python:3.7-slim-buster
#   before_script:
#     - pip install flake8
#   script:
#     - flake8 --extend-ignore E203,E501 .
#   only:
#     - merge_requests

# pylint:
#   stage: quality_checking
#   image: python:3.7-slim-buster
#   before_script:
#     - pip install pylint
#     - touch __init__.py
#   script:
#     pylint $(pwd)
#   only:
#     - merge_requests

default:
  before_script:
      - uname --nodename    
      - ulimit -s unlimited    
      - export USER=root    
      - export LOGNAME=root    
      - source /etc/profile.d/modules.sh    
      - module use /usr/local/modules/default    
      - module load standard dot FUN
      - module switch python/3.7
      - python -m venv venv
      - source venv/bin/activate
      - pip install --upgrade -U pip --quiet
      - pip install -r requirements.txt --quiet

run:
  stage: run  
  tags: 
    - freia
  script:
    - python mast2HDF5.py
  artifacts:
    paths:
      - output/
    expire_in: 1 day

compare:
  stage: tests
  tags: 
    - freia
  script:
    - pytest output_test.py