stages:
  - quality_checking

isort:
  stage: quality_checking
  image: python:3.7-slim-buster
  before_script:
    - pip install isort
  script:
    - isort --check-only --profile black .

black:
  stage: quality_checking
  image: python:3.7-slim-buster
  before_script:
    - pip install black
  script:
    - black --check .

flake8:
  stage: quality_checking
  image: python:3.7-slim-buster
  before_script:
    - pip install flake8
  script:
    - flake8 --extend-ignore E501 .

pylint:
  stage: quality_checking
  image: python:3.7-slim-buster
  before_script:
    - pip install pylint
  script:
    - touch __init__.py; pylint $(pwd); rm __init__.py
