version: '3.8'
services:
  api:
    volumes:
      - ./data:/code/data
      - ./src:/code/src
    ports:
      - "5000:5000"
    entrypoint: 
      - "uvicorn"
      - "src.api.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5000"
      - "--reload"