version: '3.8'
services:
  db:
    container_name: mysql
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ../../data:/data
      - /volumes/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: test
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

