#!/bin/bash

# Verify options and abort if there is a error
#$ -w e

# Choose parallel environment
#$ -pe openmpi 1

# Specify the job name in the queue system
#$ -N mast-prov

# Start the script in the current working directory
#$ -cwd

# Time requirements
#$ -l h_rt=120:00:00
#$ -l s_rt=120:00:00

# Specify where standard output and error are stored
#$ -o prov_log.out
#$ -e prov_log.err

source ~/envs/fmast/bin/activate
python3 -m src.create_provenance campaign_shots/M9.csv

