#!/bin/bash 
#SBATCH -A UKAEA-AP002-CPU
#SBATCH -p icelake
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=1-00:00
#SBATCH --mem=10000
#SBATCH -J create_signal_metadata
#SBATCH --output=log.%x.%j.out

source ~/.bashrc
conda activate mast

CAMPAIGN="M7"
INPUT_PATH=/home/ir-jack5/rds/rds-ukaea-mast-sPGbyCAPsJI/archive/zarr/$CAMPAIGN
OUTPUT_PATH=./data/mast/meta
NUM_WORKERS=32

python -m src.metadata.create_signal_metadata -n $NUM_WORKERS $INPUT_PATH "${OUTPUT_PATH}/${CAMPAIGN}_signals.parquet"