name: Continuous Deployment to Remote Server
on:
  push:
    branches: [ "main" ]

env:
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }} 
  PGADMIN_USER=: ${{ secrets.PGADMIN_USER }} 
  PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD }} 

jobs:
  remote_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect and Deploy on Remote Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_PRIV_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd /srv/fair-mast/
            git pull
            source .venv/bin/activate
            /home/deploy/.local/bin/uv run jb build docs --path-output src/api/static
            docker compose -f dev/docker/docker-compose.yml up --remove-orphans --build -d 


