name: CI
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and run with Docker Compose
      run: |
        docker-compose --env-file dev/docker/.env.dev -f dev/docker/docker-compose.yml up --build -d

  run-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Run tests inside Docker container
      run: |
        docker exec pg_container pip install pytest
        docker exec pg_container pytest
    
    
    - name: Shutdown container
      run: docker stop my-container && docker rm my-container




