name: CI
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: myimage/django-server:base
      ports:
        - 8000:8000
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    env:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres

    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyTest
        run: |
          pip install pytest
          pytest tests/test_mock_db.py --data-path=data/metadata/mini