name: Manual Workflow
on:
  workflow_dispatch:

jobs:
  testing_job:
    runs-on: ubuntu-latest
    
    steps:  
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Connect and Deploy on Remote Server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.REMOTE_PRIV_KEY }}
        port: ${{ secrets.REMOTE_PORT }}
        script: |
          cd /home/deploy
          mkdir Remote_Deploy_Test
