version: '3.8'
services:
  api:
    volumes:
      - ../../data:/code/data
      - ../../src:/code/src
    expose:
      - 5000
    entrypoint: 
      - "python"
      - "-m"
      - "uvicorn"
      - "src.api.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "5000"
      - "--reload"
    environment:
      - VIRTUAL_HOST=mastapp.site
      - VIRTUAL_PORT=5000
